name: inventario
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  flutter_map_mbtiles: ^1.0.0
  latlong2: 0.9.1
  mbtiles: ^0.4.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/partedelahabana.mbtiles
    - assets/tiles/tiles.mbtiles
