name: inventario
description: "Aplicacion para la recogida de características en formularios que describirán los diferentes predios o terrenos sobre los que se aplicarán impuestos basados en dichas características terrenales y/o arquitectónicas."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_mbtiles: ^1.0.4
  latlong2: 0.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  file_picker: ^10.1.0
  vector_map_tiles: ^8.0.0
  vector_map_tiles_mbtiles: ^1.0.0
  mbtiles: ^0.4.0
  vector_tile_renderer: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/tiles/
