name: inventario
description: "Aplicacion para la recogida de características en formularios que describirán los diferentes predios o terrenos sobre los que se aplicarán impuestos basados en dichas características terrenales y/o arquitectónicas."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_map_mbtiles: ^1.0.4
  geolocator: ^14.0.1
  latlong2: 0.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  file_picker: ^10.1.0
  image_picker: ^1.1.2
  mbtiles: ^0.4.0
  flutter_launcher_icons: "^0.14.3"
  circular_countdown_timer: ^0.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_icons:
  image_path: "assets/logo/logo1.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/tiles/
    - assets/Delimitations/
    - assets/logo/
